### PR TITLE
fix spurious file not exists

### PR DESCRIPTION
**Pull request by contrun**
see https://github.com/skywind3000/z.lua/issues/49

### CODE REVIEW

**Comment by skywind3000** [comment]
Thanks, would you please keep the indent ? I am using tab instead of 4-spaces

**Comment by skywind3000** [comment]
what is the return code and error message if you use rename for:

/usr/bin/

The patch introduced two additonal system call. (open/close), I am trying to minimize them for performance reason, thousand of path need to be validate when a new path add in or updating an old path. (`_zlua --add xxx`).

**Comment by contrun** [comment]
No problem. Did it.

**Comment by contrun** [comment]
I think rename only fails on read only file system. Your performance concern is reasonable. I changed the program logic to only open file on return code 30.

**Comment by skywind3000** [comment]
thanks

**Comment by skywind3000** [comment]
v1.5.4 released for this and other changes.

**Pull request merged**
