### PR TITLE
Fixes and docs for the ranger plugin

### PR DESCRIPTION
**Pull request by ilyagr**
Makes Ranger plugin use the standard `$ZLUA_LUAEXE` and `$ZLUA_SCRIPT`
environment variables that `z.lua`, fixes error handling, adds docs.

### CODE REVIEW

**Comment by ilyagr** [comment]
- Makes Ranger plugin use the standard `$ZLUA_LUAEXE` and `$ZLUA_SCRIPT`
  environment variables that `z.lua` itself uses.

- Better error handling; errors loading plugin no longer cause
  `ranger` to quit entirely.

- Briefly document the plugin

**Comment by ilyagr** [comment]
I split this PR into two commits: the first one has all the important changes in a small diff, the second one consists only of stylistic changes but has a larger diff. Let me know if I should combine them into one commit, remove the second one, etc.

**Comment by skywind3000** [comment]
thanks

**Comment by ilyagr** [comment]
Thank you! I also realized there's a [FAQ entry](https://github.com/skywind3000/z.lua/wiki/FAQ#how-to-integrate-zlua-to-ranger-) about ranger integration. You probably should delete the portion that says

> and set environment variable in your shell rc: `export RANGER_ZLUA="/path/to/z.lua"`

Or, perhaps, just replace the entry with a link to the relevant portion of README.md.

**Pull request merged**
