### PR TITLE
Some enhancement to bash fzf completion

### PR DESCRIPTION
**Pull request by BarbUk**

### CODE REVIEW

**Comment by skywind3000** [comment]
very nice !!

**Comment by skywind3000** [comment]
When I input `z vim<tab>`:

```
skywind@weilin0:~$ z vim
> vim  < 45/280
> 844         ~/software/vim
  436         /mnt/d/acm/github/vim/etc
  196         /mnt/d/acm/github/vim
  120         ~/github/vim
  32          /mnt/d/acm/github/vim-init
  20          /mnt/d/acm/github/vim/autoload
  16          /mnt/d/acm/github/vim/autoload/dash
  7.5         ~/tmp/comma/software/vim
  6           ~/.vim/vim/tools/bin
  6           ~/.vim
  4.5         ~/software/vim/src
  4           ~/.vim/vim/etc
  4           ~/.vim/vim
  2.5         ~/github/vim/autoload
  1.75        /mnt/e/lab/wind/GlobalVoice/voice/AudioCore/webrtc/modules/audio_processing/agc/include
  1.5         ~/software/vim/src/libvterm
```

and accept the first result, the command line becomes:

    skywind@weilin0:~$ z 844         ~/software/vim

can we eliminate that `844` ??

**Comment by skywind3000** [comment]
`z -I vim` doesn't have a `844`

**Comment by BarbUk** [comment]
> can we eliminate that 844 ??

Yes, i forgot to filter the return value.
It's fixed with https://github.com/skywind3000/z.lua/pull/40

**Pull request merged**
